# Generated by Django 5.1.7 on 2025-04-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_endereco_salao_telefonesalao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telefonesalao',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_festa', models.DateTimeField(unique=True, verbose_name='Data da festa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('desc_festa', models.TextField(verbose_name='Descrição da festa')),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salao', verbose_name='Salão')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('salao', 'data_festa'), name='unico_aluguel_por_salao_e_data')],
            },
        ),
    ]
