# Generated by Django 5.1.7 on 2025-04-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_telefonesalao_unique_together_aluguel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_festa',
            field=models.DateTimeField(verbose_name='Data da festa'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='salao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salao', verbose_name='Salao'),
        ),
        migrations.AlterField(
            model_name='salao',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='telefonesalao',
            name='salao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='core.salao', verbose_name='Saloes'),
        ),
    ]
