# Generated by Django 5.1.7 on 2025-04-10 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aluguel_data_festa_alter_aluguel_salao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonesalao',
            name='salao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='core.salao', verbose_name='Salao'),
        ),
    ]
