# Generated by Django 5.2 on 2025-04-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_decoracao_alter_aluguel_options_alter_salao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='salao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.salao', verbose_name='Salão'),
        ),
        migrations.CreateModel(
            name='FotoDecoracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='decoracoes/', verbose_name='Imagem da decoração')),
                ('decoracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.decoracao', verbose_name='Decoração')),
            ],
            options={
                'verbose_name_plural': 'Fotos de Decorações',
            },
        ),
    ]
