# Generated by Django 5.2 on 2025-04-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fotodecoracao_imagem'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='decoracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.decoracao', verbose_name='Decoração'),
        ),
        migrations.AlterField(
            model_name='fotodecoracao',
            name='decoracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_decoracao', to='core.decoracao', verbose_name='Decoração'),
        ),
        migrations.AlterField(
            model_name='fotodecoracao',
            name='imagem',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image', verbose_name='Imagem'),
        ),
    ]
