# Generated by Django 5.2 on 2025-06-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aluguel_decoracao_alter_fotodecoracao_decoracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='decoracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.decoracao', verbose_name='Decoração'),
        ),
    ]
