# Generated by Django 5.2 on 2025-06-13 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_aluguel_decoracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
