# Generated by Django 5.2 on 2025-06-13 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='tipo_locacao',
            field=models.CharField(blank=True, choices=[('SALAO', 'Salão'), ('DECORACAO', 'Decoração'), ('AMBOS', 'Salão e Decoração')], max_length=10, null=True, verbose_name='Tipo_da_locação'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_festa',
            field=models.DateTimeField(verbose_name='Data_da_festa'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='decoracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.decoracao', verbose_name='Decoração'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='desc_festa',
            field=models.TextField(verbose_name='Descrição_da_festa'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='salao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.salao', verbose_name='Salão'),
        ),
    ]
