# Generated by Django 5.2 on 2025-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aluguel_tipo_locacao_alter_aluguel_data_festa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'verbose_name_plural': 'Aluguéis'},
        ),
        migrations.RemoveConstraint(
            model_name='aluguel',
            name='unico_aluguel_por_salao_e_data',
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_festa',
            field=models.DateField(verbose_name='Data da festa'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='desc_festa',
            field=models.TextField(verbose_name='Descrição da festa'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='tipo_locacao',
            field=models.CharField(choices=[('SALAO', 'Salão'), ('DECORACAO', 'Decoração'), ('AMBOS', 'Salão e Decoração')], default='SALAO', max_length=10, verbose_name='Tipo da locação'),
        ),
    ]
