# Generated by Django 5.2 on 2025-08-29 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_phone_alter_fotodecoracao_imagem'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotodecoracao',
            name='imagem',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image', verbose_name='Imagem'),
        ),
    ]
