# Generated by Django 5.2 on 2025-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_fotodecoracao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='valor_festa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor total da festa'),
        ),
    ]
