# Generated by Django 5.2 on 2025-09-15 17:17

import django.db.models.deletion
import setuptools._vendor.jaraco.context
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aluguel_valor_festa'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeResponsavel', models.CharField(max_length=255)),
                ('nomeServico', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.CharField(unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='tipo_locacao',
            field=models.CharField(choices=[('SALÃO', 'Salão'), ('DECORAÇÃO', 'Decoração'), ('AMBOS', 'Salão e Decoração')], default='SALAO', max_length=10, verbose_name='Tipo da locação'),
        ),
        migrations.AlterField(
            model_name='fotodecoracao',
            name='imagem',
            field=models.ForeignKey(blank=True, default=setuptools._vendor.jaraco.context.null, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='servico',
            field=models.ManyToManyField(blank=True, related_name='servico', to='core.servicoadicional'),
        ),
    ]
