# Generated by Django 5.2 on 2025-09-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_user_phone_alter_telefonesalao_salao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
