# Generated by Django 5.2 on 2025-10-15 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_aluguel_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotodecoracao',
            name='decoracao',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='decoracao',
        ),
        migrations.RemoveField(
            model_name='fotodecoracao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='salao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='salao',
        ),
        migrations.RemoveField(
            model_name='telefonesalao',
            name='salao',
        ),
        migrations.RenameField(
            model_name='aluguel',
            old_name='data_festa',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='tipo_locacao',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='status',
            field=models.CharField(choices=[('PAGO', 'Salão'), ('PENDENTE', 'Decoração')], default='PENDENTE', max_length=10, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('nota', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Decoracao',
        ),
        migrations.DeleteModel(
            name='FotoDecoracao',
        ),
        migrations.DeleteModel(
            name='Salao',
        ),
        migrations.DeleteModel(
            name='TelefoneSalao',
        ),
    ]
