# Generated by Django 5.2 on 2025-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_fotodecoracao_decoracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='status',
            field=models.CharField(choices=[('PAGO', 'pago'), ('PENDENTE', 'pendente')], default='PENDENTE', max_length=10, verbose_name='status'),
        ),
    ]
