# Generated by Django 5.2 on 2025-10-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_aluguel_status'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicoadicional',
            options={'verbose_name_plural': 'Serviços Adicionais'},
        ),
        migrations.RemoveField(
            model_name='servicoadicional',
            name='email',
        ),
        migrations.RemoveField(
            model_name='servicoadicional',
            name='nomeResponsavel',
        ),
        migrations.RemoveField(
            model_name='servicoadicional',
            name='numero',
        ),
        migrations.AddField(
            model_name='servicoadicional',
            name='foto_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servico_foto', to='uploader.image'),
        ),
    ]
