# Generated by Django 5.2 on 2025-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_servicoadicional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data',
            field=models.DateTimeField(verbose_name='Data da festa'),
        ),
    ]
